* Moena-DWM
This is my own personal build of the Suckless Dynamic Window Manager, [[https://dwm.suckless.org/][DWM]].

Currently using DWM version 6.5, the latest as of June 2025.

This DWM build is not heavily patched. In fact, I am only using five patches:

- =dwm-colemak_keys-20200907-61bb8b2.diff= from [[https://dwm.suckless.org/patches/colemak_keys/]]
- =dwm-cool_autostart-6.5.diff= from [[https://dwm.suckless.org/patches/cool_autostart/]]
- =dwm-vanitygaps-6.4.diff= from [[https://dwm.suckless.org/patches/vanitygaps/]]
- =dwm-barpadding-20211020-a786211.diff= from [[https://dwm.suckless.org/patches/barpadding/]]
- =dwm-colorschemes-6.5.diff= from [[https://dwm.suckless.org/patches/colorschemes/]]

I have created then created a couple of patches for my changes in order to keep the source tree clean:

- =cmds_autostart.diff=
- =monocle_gaps.diff=
- =fixes.diff=

I am using [[https://savannah.nongnu.org/projects/quilt][Quilt]] to manage the patches.

To build and install, I run `quilt push -a` to apply all the patches, followed by `rebuild.sh`.

I then run `quilt pop -a` to un-apply the patches and return to a state that is either pristine or in need of a git commit (because one patch was updated).

Keeping all changes in patches makes it much easier to upgrade DWM to a new version when that happens.
